import './global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ably & Next.js fundamentals kit',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='flex px-10 py-4 bg-gray-200'>
          <h1 className='font-bold text-2xl tracking-tighter'>
            Collaborate <span className='text-purple-600'>Masterpiece</span>
          </h1>
        </nav>
        <main className=''>{children}</main>
      </body>
    </html>
  )
}
